# Generated by Django 4.0.4 on 2022-05-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default=' ', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('sub_city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('woreda', models.CharField(max_length=10)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('sub_city', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=10)),
                ('symptoms', models.TextField(max_length=500)),
                ('bmi', models.FloatField(max_length=5)),
                ('temperature', models.FloatField(max_length=5)),
                ('blood_pressure', models.FloatField(max_length=5)),
                ('heart_beat', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('sub_city', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=10)),
                ('profile_picture', models.CharField(default=' ', max_length=300)),
                ('description', models.TextField(default=' ', max_length=500)),
                ('isActive', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaria.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='Pending', max_length=100)),
                ('cell_image', models.CharField(max_length=300)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to='malaria.registeredpersonnel')),
                ('lab_technician_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lab_Technician', to='malaria.registeredpersonnel')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaria.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=200)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaria.registeredpersonnel')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaria.patient')),
            ],
        ),
    ]
