# Generated by Django 3.2.13 on 2022-05-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='heart_beat',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='temperature',
        ),
        migrations.CreateModel(
            name='PatientCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField(max_length=5)),
                ('temperature', models.FloatField(max_length=5)),
                ('blood_pressure', models.FloatField(max_length=5)),
                ('heart_beat', models.FloatField(max_length=5)),
                ('fever', models.BooleanField(default=False)),
                ('chills', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('diarrhea', models.BooleanField(default=False)),
                ('abdominal_pain', models.BooleanField(default=False)),
                ('muscle_pain', models.BooleanField(default=False)),
                ('joint_pain', models.BooleanField(default=False)),
                ('rapid_breathing', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('rapid_heart_rate', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaria.patient')),
            ],
        ),
    ]
