# Generated by Django 3.2.13 on 2022-06-06 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('malaria', '0002_auto_20220529_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credential',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='doctor_name',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='patient_name',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='requestdiagnostic',
            old_name='doctor_name',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='requestdiagnostic',
            old_name='lab_technician_name',
            new_name='lab_technician',
        ),
        migrations.RemoveField(
            model_name='requestdiagnostic',
            name='cell_image',
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hosptals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeredpersonnel',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='sub_city',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='woreda',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientcheckup',
            name='patient',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='malaria.patient'),
        ),
        migrations.AlterField(
            model_name='registeredpersonnel',
            name='city',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='registeredpersonnel',
            name='email',
            field=models.EmailField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='registeredpersonnel',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='registeredpersonnel',
            name='phone',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='registeredpersonnel',
            name='profile_picture',
            field=models.ImageField(default=' ', max_length=300, upload_to=''),
        ),
        migrations.AlterField(
            model_name='registeredpersonnel',
            name='sub_city',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='registeredpersonnel',
            name='woreda',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
