# Generated by Django 3.2.13 on 2022-06-06 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('malaria', '0003_auto_20220606_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosptals', to=settings.AUTH_USER_MODEL),
        ),
    ]
