# Generated by Django 3.2.13 on 2022-05-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('sub_city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('woreda', models.CharField(max_length=10)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('sub_city', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=10)),
                ('symptoms', models.TextField(max_length=500)),
                ('bmi', models.FloatField(max_length=5)),
                ('temperatur', models.FloatField(max_length=5)),
                ('blood_pressure', models.FloatField(max_length=5)),
                ('heart_beat', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('sub_city', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=10)),
                ('profile_picture', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=500)),
                ('hospital_id', models.IntegerField(max_length=10)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('medicine_name', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDiagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('result', models.CharField(default='Pending', max_length=100)),
                ('doctor_name', models.CharField(max_length=200)),
                ('lab_technician_name', models.CharField(max_length=200)),
                ('cell_image', models.CharField(max_length=300)),
            ],
        ),
    ]
