# Generated by Django 4.0.4 on 2022-05-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials',
            new_name='Credential',
        ),
        migrations.RenameModel(
            old_name='RequestDiagnostics',
            new_name='RequestDiagnostic',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='temperatur',
            new_name='temperature',
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='hospital_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
